/*

Title: PIC compression
Author: Abbas A. Fairouz
Version: 1.0
Created: Sep. 17, 2024
Updated: Sep. 17, 2024

Word frequency reference:
https://www.kaggle.com/datasets/rtatman/english-word-frequency?resource=download

Added extra for test

*/


#include <iostream>
#include <fstream>
#include <sstream>
#include <unordered_map>  // hash table library: (key,value) pair
#include <string>
#include <math.h>  // math library

#define ONE_BYTE_BOUND pow(2,7)
#define TWO_BYTE_BOUND pow(2,14)
//#define TWO_BYTE_MID (pow(2,7)-1) << 7
#define THREE_BYTE_BOUND pow(2,21)


using namespace std;

int main() {

    // **** TESTs ****
    int TMP_NUM = ONE_BYTE_BOUND-1;
    const int TWO_BYTE_MID = TMP_NUM << 7;
    cout << "Two byte mid = " << TWO_BYTE_MID << "bits = " << bitset<14> (TWO_BYTE_MID) << endl;
    // ****************

    // File path of the CSV file
    string filename = "unigram_freq.csv"; 
    uint8_t byteCode;
    uint8_t byteCode1, byteCode2, byteCode3;

    // Open the CSV file
    ifstream file(filename);

    // Check if the file is open
    if (!file.is_open()) {
        cerr << "Error opening file: " << filename << endl;
        return 1;
    }

    // Declare the unordered_map to store the word and serialized integer
    unordered_map<string, int> wordMap;
    
    // Variables to store each line and word
    string line, word;
    int serial = 3; // Start serializing from 1
    int tmpSerial;

    /*
    *** Generate T0 ***
    Have reserved values:
    1) Space                => 0x0
    2) New line             => 0x1
    3) Next Capital letter  => 0x2
    */

    // Read the file line by line
    while (getline(file, line)) {
        stringstream ss(line); // Use a stringstream to parse the line
        string temp; // To hold the "count" column which we will ignore
        
        // Get the word from the line
        getline(ss, word, ','); 
        getline(ss, temp, ','); // Ignore the second column (count)

        
        wordMap[word] = serial;

        if(serial >= 0 && serial < ONE_BYTE_BOUND){ // ONE BYTE encoding [0 : (2^7) - 1]
            cout << "Word: " << word << ", Serial: " << int(serial) << endl;
            tmpSerial = serial;
            byteCode = tmpSerial << 1;
            wordMap[word] = byteCode;
            // cout << "Generated Byte (Hex): " << hex << int(byteCode) << endl;
            // cout << "Generated Byte (Binary): " << bitset<8>(byteCode) << endl;
        }
        else if(serial >= ONE_BYTE_BOUND && serial < TWO_BYTE_BOUND + ONE_BYTE_BOUND){ // TWO BYTE encoding [0 : (2^14) - 1]
            if(serial >= 2^7 && serial < 2^14){

            }

        }
        //else{
            // Add word to the map with the current serial number
            //wordMap[word] = serial;
        //}
            


        serial++;

        // You can print the word and its serialized value for debugging
        //cout << "Word: " << word << ", Serial: " << wordMap[word] << endl;
    }

    // Close the file after reading
    file.close();




    cout << "\nTotal words = " << serial-1 << "\n\n";
    cout << "The hash map has been generated successfully!\n\n";

    // Test the hash map

    cout << "Test the hash map:\n";
    string tmp_word = "of";
    byteCode = wordMap[tmp_word];
    cout << "Word (" << tmp_word << ") has an order of: " << byteCode << "\n";
    cout << "Generated Byte (Hex): " << hex << int(byteCode) << endl;
    cout << "Generated Byte (Binary): " << bitset<8>(byteCode) << endl;


    cout << "\n\n";


    

    return 0;
}

