/*

Title: Enhanced PIC (EPIC) compression
Author: Abbas A. Fairouz
Version: 1.0
Created: Sep. 17, 2024
Updated: Nov. 13, 2024

Word frequency reference:
https://www.kaggle.com/datasets/rtatman/english-word-frequency?resource=download

*/


#include <iostream>
#include <fstream>
#include <sstream>
#include <unordered_map>  // hash table library: (key,value) pair
#include <string>
#include <math.h>  // math library

#define TWO_SEVEN pow(2,7)
#define TWO_FOURTEEN pow(2,14)

/*
*** Notes for the byte codes range calculations ***
- Byte Code 1: BC1
- Byte Code 2: BC2
- Byte Code 3: BC3

0, 1, 2: reserved codes for the BC1
BC1 range:       3         --> (2^7) - 1
BC2 range:     (2^7)       --> (2^7) + (2^14) - 1
BC3 range: (2^7) + (2^14)  --> (2^7) + (2^14) + (2^21) - 1

BC2 offset: (2^7)
BC3 offset: (2^7) + (2^14)

*** Comments:
Dictionary table - implementation options:
1. Create multiple hash map tables: BC1 hash map, BC2 hash map, ... etc    ??
2. ..



*/



#define TWO_BYTE_OFFSET pow(2,7)
#define THREE_BYTE_OFFSET pow(2,7) + pow(2,14)
#define ONE_BYTE_BOUND pow(2,7) - 1
#define ONE_BYTE_LOWER_BOUND 3
#define TWO_BYTE_BOUND pow(2,7) + pow(2,14) - 1
//#define TWO_BYTE_MID (pow(2,7)-1) << 7
#define THREE_BYTE_BOUND pow(2,7) + pow(2,14) + pow(2,21) - 1 

uint32_t MASK_BYTE = 0x0000007f; // Mask value for the least significant byte (LSB)

void TWO_BYTE_CODE_GENERATOR(uint32_t input);
void THREE_BYTE_CODE_GENERATOR(uint32_t input);

uint8_t Mask_Single_Byte(uint32_t number);
uint32_t Shift_Left_with_One_Inserted(uint32_t number);
uint32_t Shift_Left_with_Zero_Inserted(uint32_t number);
uint32_t Shift_Right_Seven_Positions(uint32_t number);

using namespace std;

int main() {

    // **** TESTs ****
    int TMP_NUM = ONE_BYTE_BOUND-1;
    const int TWO_BYTE_MID = TMP_NUM << 7;
    cout << "Two byte mid = " << TWO_BYTE_MID << "bits = " << bitset<14> (TWO_BYTE_MID) << endl;
    // ****************

    // File path of the CSV file
    string filename = "unigram_freq.csv"; 
    uint8_t byteCode;
    uint8_t byteCode1, byteCode2, byteCode3;

    // Open the CSV file
    ifstream file(filename);

    // Check if the file is open
    if (!file.is_open()) {
        cerr << "Error opening file: " << filename << endl;
        return 1;
    }

    // Declare the unordered_map to store the word and serialized integer
    unordered_map<string, int> wordMap;
    
    // Variables to store each line and word
    string line, word;
    int serial = 3; // Start serializing from 1
    int tmpSerial;
    uint32_t input;

    /*
    *** Generate T0 ***
    Have reserved values:
    1) Space                => 0x0
    2) New line             => 0x1
    3) Next Capital letter  => 0x2
    */

    // Read the file line by line
    while (getline(file, line)) {
        stringstream ss(line); // Use a stringstream to parse the line
        string temp; // To hold the "count" column which we will ignore
        
        // Get the word from the line
        getline(ss, word, ','); 
        getline(ss, temp, ','); // Ignore the second column (count)

        
        wordMap[word] = serial;

        if(serial >= ONE_BYTE_LOWER_BOUND && serial < ONE_BYTE_BOUND){ // ONE BYTE encoding 
            cout << "Word: " << word << ", Serial: " << int(serial) << endl;
            tmpSerial = serial;
            byteCode = tmpSerial << 1;
            wordMap[word] = byteCode;
            // cout << "Generated Byte (Hex): " << hex << int(byteCode) << endl;
            // cout << "Generated Byte (Binary): " << bitset<8>(byteCode) << endl;
        }
        else if(serial >= TWO_BYTE_OFFSET && serial < TWO_BYTE_BOUND){ // TWO BYTE encoding
            input = serial - TWO_BYTE_OFFSET;

        }
        if(serial >= THREE_BYTE_OFFSET && serial < THREE_BYTE_BOUND){
            input = serial - THREE_BYTE_OFFSET;
        }
        //else{
            // Add word to the map with the current serial number
            //wordMap[word] = serial;
        //}
            


        serial++;

        // You can print the word and its serialized value for debugging
        //cout << "Word: " << word << ", Serial: " << wordMap[word] << endl;
    }

    // Close the file after reading
    file.close();




    cout << "\nTotal words = " << serial-1 << "\n\n";
    cout << "The hash map has been generated successfully!\n\n";

    // Test the hash map

    cout << "Test the hash map:\n";
    string tmp_word = "of";
    byteCode = wordMap[tmp_word];
    cout << "Word (" << tmp_word << ") has an order of: " << byteCode << "\n";
    cout << "Generated Byte (Hex): " << hex << int(byteCode) << endl;
    cout << "Generated Byte (Binary): " << bitset<8>(byteCode) << endl;


    cout << "\n\n";


    

    return 0;
} // main function



/* OTHER FUNCTIONS */

/*
'TWO_BYTE_CODE_GENERATOR' function:
Generate a 2-byte code of EPIC algorithm
*/
void TWO_BYTE_CODE_GENERATOR(uint32_t input)
{
    uint8_t byte1 = Mask_Single_Byte(input); // mask the LSb of 'DICT_ORDER_NUM' using mask1, store it in 'byte1'
    byte1 = Shift_Left_with_One_Inserted(byte1); // shift 'byte1' to the left by 1, and insert '1' as the LSb
    
    uint8_t byte2 = Shift_Right_Seven_Positions(input); // shift 'DICT_ORDER_NUM' to the right by 7 positions
    byte2 = Shift_Left_with_Zero_Inserted(byte2); // shift 'DICT_ORDER_NUM_shift' to the left by 1 position
    
}


/*
'THREE_BYTE_CODE_GENERATOR' function:
Generate a 3-byte code of EPIC algorithm
*/
void THREE_BYTE_CODE_GENERATOR(uint32_t input)
{
    cout << endl << endl;
    cout << "Testing the 'THREE BYTE CODE' generation in EPIC:\n";
    cout << "-----------------------------------------------\n\n";
    cout << "Generate a random number of 21 bits size. (3 sets of 7 bits: 7 x 3 = 21)\n";
    cout << "This random number will be used later from\nthe order of the word in the dictionary.\n\n";

    cout << "Random number generated:\n";
    cout << "DICT_ORDER_NUM = " << bitset<32>(input) << endl; // print 'DICT_ORDER_NUM' as 16-bit
    cout << endl;

    cout << "Generate the mask for the least 7 significant bits (LSb-7):\n";
    cout << "mask1 = " << bitset<32>(MASK_BYTE) << endl; // print the 'mask1' value as 16 bits 
    cout << endl;
    
    cout << "Generate the 1st BYTE CODE:\n";
    cout << "* Mask the DICT_ORDER_NUM with mask1 *\n";
    uint16_t byte1 = Mask_Single_Byte(input); // mask the LSb of 'DICT_ORDER_NUM' using mask1, store it in 'byte1'
    cout << "DICT_ORDER_NUM & mask1 = " << bitset<8>(byte1) << endl; // print the LSb masked value of 'DICT_ORDER_NUM'
    cout << "* shift 'byte1' to the left by 1, and insert '1' as the LSb *\n";
    byte1 = Shift_Left_with_One_Inserted(byte1); // shift 'byte1' to the left by 1, and insert '1' as the LSb
    cout << "BYTE CODE 1 = " << bitset<8>(byte1) << endl; // BYTE CODE 1: 'byte1' has the 1st BYTE CODE 
    cout << endl;
    
    cout << "Generate the 2nd BYTE CODE:";
    cout << "* shift 'DICT_ORDER_NUM' to the right by 7 positions *\n";
    uint32_t input_shitf1 = Shift_Right_Seven_Positions(input); // shift 'DICT_ORDER_NUM' to the right by 7 positions
    cout << "DICT_ORDER_NUM shift >> 7 = " << bitset<32>(input_shitf1) << endl; // print the shifted value of 'DICT_ORDER_NUM'
    uint8_t byte2 = Mask_Single_Byte(input_shitf1); // mask the LSb of 'DICT_ORDER_NUM' using mask1, store it in 'byte1'
    cout << "DICT_ORDER_NUM shift & mask1 = " << bitset<8>(byte2) << endl; // print the LSb masked value of 'DICT_ORDER_NUM'
    cout << "* shift 'byte2' to the left by 1, and insert '1' as the LSb *\n";
    byte2 = Shift_Left_with_One_Inserted(byte2); // shift 'byte2' to the left by 1, and insert '1' as the LSb
    cout << "BYTE CODE 2 = " << bitset<8>(byte2) << endl; // BYTE CODE 2: 'byte2' has the 2nd BYTE CODE 
    cout << endl;

    cout << "Generate the 3rd BYTE CODE:";
    cout << "* shift 'DICT_ORDER_NUM' to the right by 7 positions *\n";
    uint8_t byte3 = Shift_Right_Seven_Positions(input_shitf1); // shift 'DICT_ORDER_NUM' to the right by 7 positions
    cout << "DICT_ORDER_NUM shift >> 7 = " << bitset<8>(byte3) << endl; // print the shifted value of 'DICT_ORDER_NUM'
    cout << endl;
    
    byte3 = byte3 << 1; // shift 'DICT_ORDER_NUM_shift' to the left by 1 position
    cout << "BYTE CODE 3 = " << bitset<8>(byte3) << endl; // BYTE CODE 2: 'byte3' has the 2nd BYTE CODE 
    cout << endl;
}

// To mask the least significant byte
uint8_t Mask_Single_Byte(uint32_t number){
    return MASK_BYTE & number;
}

// Shift a number to the left by one position,
// and insert '1' as the LSbit.
uint32_t Shift_Left_with_One_Inserted(uint32_t number){
    return number << 1 | (0x1);
}

// Shift a number to the left by one position,
// and insert '0' as the LSbit.
uint32_t Shift_Left_with_Zero_Inserted(uint32_t number){
    return number << 1;
}

uint32_t Shift_Right_Seven_Positions(uint32_t number){
    return number >> 7;
}


// Check if the least significant bit (LSb) is one.
// If LSb is '1', then there is another byte code in the sequence.
// This function is used in the decompression process.
uint8_t Next_Byte_Available(uint8_t number){
    //return number % 2; // return one or zero.
    return number & (0x1); // return one or zero: mask it with the LSb
}

